### ISSUE TITLE
Am i doing something wrong?

### ISSUE THREAD

**Issue by Ademord** [janosh/tensorboard-reducer#16]
I can't seem to use your tool, could you please help me
```
ubuntu@unity-1:~/ultron/configLoader_v4/scripts$ echo event_files/run*
event_files/run61-explore event_files/run61-explore-constrained event_files/run61-explore-constrained.events.out.tfevents.1640984794.unity-3.23065.0 event_files/run61-explore.events.out.tfevents.1640984794.unity-2.25875.0 event_files/run61-voxel event_files/run61-voxel-constrained event_files/run61-voxel-constrained.events.out.tfevents.1640984794.unity-5.23094.0 event_files/run61-voxel.events.out.tfevents.1640984794.unity-4.25035.0 event_files/run62-16 event_files/run62-16-constrained event_files/run62-16-constrained-pigeon-pathak event_files/run62-16-constrained-pigeon-pathak.events.out.tfevents.1641647188.unity-7.105591.0 event_files/run62-16-constrained.events.out.tfevents.1640984794.unity-7.22654.0 event_files/run62-16-pathak event_files/run62-16-pathak.events.out.tfevents.1641156311.unity-3.59657.0 event_files/run62-16-pathak.events.out.tfevents.1641332673.unity-3.84443.0 event_files/run62-16-pathak.events.out.tfevents.1641486791.unity-3.94913.0 event_files/run62-16-pathak.events.out.tfevents.1641646666.unity-3.120988.0 event_files/run62-16.events.out.tfevents.1640984794.unity-6.22114.0 event_files/run62-16.events.out.tfevents.1641152748.unity-6.64103.0 event_files/run62-16.events.out.tfevents.1641332776.unity-6.2450.0 event_files/run62-16.events.out.tfevents.1641486791.unity-6.34914.0 event_files/run62-4 event_files/run62-4-pathak event_files/run62-4-pathak.events.out.tfevents.1641084257.unity-1.64003.0 event_files/run62-4-pathak.events.out.tfevents.1641488596.unity-1.120929.0 event_files/run62-4-pigeon event_files/run62-4-pigeon-pathak event_files/run62-4-pigeon-pathak.events.out.tfevents.1641214429.unity-5.53019.0 event_files/run62-4-pigeon.events.out.tfevents.1641214443.unity-4.56497.0 event_files/run62-4.events.out.tfevents.1640908535.unity-1.29477.0 event_files/run62-8 event_files/run62-8-pathak event_files/run62-8-pathak.events.out.tfevents.1641166218.unity-2.2484.0 event_files/run62-8-pathak.events.out.tfevents.1641332673.unity-2.52881.0 event_files/run62-8.events.out.tfevents.1640984805.unity-8.25270.0 event_files/run63 event_files/run63++025 event_files/run63++025.events.out.tfevents.1641156311.unity-7.47443.0 event_files/run63++050 event_files/run63++050.events.out.tfevents.1641214425.unity-8.61785.0 event_files/run63++075 event_files/run63++075.events.out.tfevents.1641253795.unity-1.82901.0 event_files/run63++100 event_files/run63++100.events.out.tfevents.1641564949.unity-2.108234.0 event_files/run63.events.out.tfevents.1641582798.unity-6.58995.0 event_files/run64 event_files/run64+vision event_files/run64+vision.events.out.tfevents.1641488480.unity-5.139102.0 event_files/run64.events.out.tfevents.1641488481.unity-4.89160.0 event_files/run65 event_files/run65-pure event_files/run65-pure.events.out.tfevents.1641488480.unity-8.123582.0 event_files/run65.events.out.tfevents.1641416393.unity-7.76235.0

ubuntu@unity-1:~/ultron/configLoader_v4/scripts$ ls event_files/
run61-explore                                                                       run62-16.events.out.tfevents.1640984794.unity-6.22114.0               run63
run61-explore-constrained                                                           run62-16.events.out.tfevents.1641152748.unity-6.64103.0               run63++025
run61-explore-constrained.events.out.tfevents.1640984794.unity-3.23065.0            run62-16.events.out.tfevents.1641332776.unity-6.2450.0                run63++025.events.out.tfevents.1641156311.unity-7.47443.0
run61-explore.events.out.tfevents.1640984794.unity-2.25875.0                        run62-16.events.out.tfevents.1641486791.unity-6.34914.0               run63++050
run61-voxel                                                                         run62-4                                                               run63++050.events.out.tfevents.1641214425.unity-8.61785.0
run61-voxel-constrained                                                             run62-4-pathak                                                        run63++075
run61-voxel-constrained.events.out.tfevents.1640984794.unity-5.23094.0              run62-4-pathak.events.out.tfevents.1641084257.unity-1.64003.0         run63++075.events.out.tfevents.1641253795.unity-1.82901.0
run61-voxel.events.out.tfevents.1640984794.unity-4.25035.0                          run62-4-pathak.events.out.tfevents.1641488596.unity-1.120929.0        run63++100
run62-16                                                                            run62-4-pigeon                                                        run63++100.events.out.tfevents.1641564949.unity-2.108234.0
run62-16-constrained                                                                run62-4-pigeon-pathak                                                 run63.events.out.tfevents.1641582798.unity-6.58995.0
run62-16-constrained-pigeon-pathak                                                  run62-4-pigeon-pathak.events.out.tfevents.1641214429.unity-5.53019.0  run64
run62-16-constrained-pigeon-pathak.events.out.tfevents.1641647188.unity-7.105591.0  run62-4-pigeon.events.out.tfevents.1641214443.unity-4.56497.0         run64+vision
run62-16-constrained.events.out.tfevents.1640984794.unity-7.22654.0                 run62-4.events.out.tfevents.1640908535.unity-1.29477.0                run64+vision.events.out.tfevents.1641488480.unity-5.139102.0
run62-16-pathak                                                                     run62-8                                                               run64.events.out.tfevents.1641488481.unity-4.89160.0
run62-16-pathak.events.out.tfevents.1641156311.unity-3.59657.0                      run62-8-pathak                                                        run65
run62-16-pathak.events.out.tfevents.1641332673.unity-3.84443.0                      run62-8-pathak.events.out.tfevents.1641166218.unity-2.2484.0          run65-pure
run62-16-pathak.events.out.tfevents.1641486791.unity-3.94913.0                      run62-8-pathak.events.out.tfevents.1641332673.unity-2.52881.0         run65-pure.events.out.tfevents.1641488480.unity-8.123582.0
run62-16-pathak.events.out.tfevents.1641646666.unity-3.120988.0                     run62-8.events.out.tfevents.1640984805.unity-8.25270.0                run65.events.out.tfevents.1641416393.unity-7.76235.0

ubuntu@unity-1:~/ultron/configLoader_v4/scripts$ tb-reducer event_files/run* -o events_reduced.csv -r mean,std,min,max
usage: TensorBoard Reducer [-h] [-i INDIRS_GLOB] [-o OUTPATH] [-r REDUCE_OPS] [-f] [--lax-tags] [--lax-steps] [--handle-dup-steps {keep-first,keep-last,mean}] [--min-runs-per-step MIN_RUNS_PER_STEP] [-v]
TensorBoard Reducer: error: unrecognized arguments: event_files/run61-explore event_files/run61-explore-constrained event_files/run61-explore-constrained.events.out.tfevents.1640984794.unity-3.23065.0 event_files/run61-explore.events.out.tfevents.1640984794.unity-2.25875.0 event_files/run61-voxel event_files/run61-voxel-constrained event_files/run61-voxel-constrained.events.out.tfevents.1640984794.unity-5.23094.0 event_files/run61-voxel.events.out.tfevents.1640984794.unity-4.25035.0 event_files/run62-16 event_files/run62-16-constrained event_files/run62-16-constrained-pigeon-pathak event_files/run62-16-constrained-pigeon-pathak.events.out.tfevents.1641647188.unity-7.105591.0 event_files/run62-16-constrained.events.out.tfevents.1640984794.unity-7.22654.0 event_files/run62-16-pathak event_files/run62-16-pathak.events.out.tfevents.1641156311.unity-3.59657.0 event_files/run62-16-pathak.events.out.tfevents.1641332673.unity-3.84443.0 event_files/run62-16-pathak.events.out.tfevents.1641486791.unity-3.94913.0 event_files/run62-16-pathak.events.out.tfevents.1641646666.unity-3.120988.0 event_files/run62-16.events.out.tfevents.1640984794.unity-6.22114.0 event_files/run62-16.events.out.tfevents.1641152748.unity-6.64103.0 event_files/run62-16.events.out.tfevents.1641332776.unity-6.2450.0 event_files/run62-16.events.out.tfevents.1641486791.unity-6.34914.0 event_files/run62-4 event_files/run62-4-pathak event_files/run62-4-pathak.events.out.tfevents.1641084257.unity-1.64003.0 event_files/run62-4-pathak.events.out.tfevents.1641488596.unity-1.120929.0 event_files/run62-4-pigeon event_files/run62-4-pigeon-pathak event_files/run62-4-pigeon-pathak.events.out.tfevents.1641214429.unity-5.53019.0 event_files/run62-4-pigeon.events.out.tfevents.1641214443.unity-4.56497.0 event_files/run62-4.events.out.tfevents.1640908535.unity-1.29477.0 event_files/run62-8 event_files/run62-8-pathak event_files/run62-8-pathak.events.out.tfevents.1641166218.unity-2.2484.0 event_files/run62-8-pathak.events.out.tfevents.1641332673.unity-2.52881.0 event_files/run62-8.events.out.tfevents.1640984805.unity-8.25270.0 event_files/run63 event_files/run63++025 event_files/run63++025.events.out.tfevents.1641156311.unity-7.47443.0 event_files/run63++050 event_files/run63++050.events.out.tfevents.1641214425.unity-8.61785.0 event_files/run63++075 event_files/run63++075.events.out.tfevents.1641253795.unity-1.82901.0 event_files/run63++100 event_files/run63++100.events.out.tfevents.1641564949.unity-2.108234.0 event_files/run63.events.out.tfevents.1641582798.unity-6.58995.0 event_files/run64 event_files/run64+vision event_files/run64+vision.events.out.tfevents.1641488480.unity-5.139102.0 event_files/run64.events.out.tfevents.1641488481.unity-4.89160.0 event_files/run65 event_files/run65-pure event_files/run65-pure.events.out.tfevents.1641488480.unity-8.123582.0 event_files/run65.events.out.tfevents.1641416393.unity-7.76235.0
```

**Comment by janosh** [comment]
Bit hard to infer your directory structure from the output you posted. File tree would be better. All the positional arguments to `tb-reducer` should be run directories containing event files. Is that the case?

**Comment by Ademord** [comment]
i have the event files directly and also as a "copy" for example folder run62-16 is a folder which contains a the event file shown in the base folder run162 `run62-16.events.out.tfevents.1640984794.unity-6.22114.0`

**Comment by janosh** [comment]
Ah, didn't spot it on my phone before. Taking a closer look at your log, it seems you're using an outdated version of `tb-reducer` that still expects a glob string to be passed to the `-i` flag. Recommended fix would be to update `pip install -U tensorboard-reducer`. Afterwards make sure you're running the latest v0.2.3.

**Comment by Ademord** [comment]
thanks for your response! 
i have done that and checked  with
```
ubuntu@unity-1:~/ultron/configLoader_v4/scripts$ pip freeze | grep reducer
tensorboard-reducer==0.2.3
```

i unfortunately still get the same
```
TensorBoard Reducer: error: unrecognized arguments: event_files/run61-explore 
```

**Comment by janosh** [comment]
That's odd. The usage help below error says

usage: TensorBoard Reducer [-h] [-i INDIRS_GLOB] [-o OUTPATH] [-r REDUCE_OPS]

The -i flag no longer exists in the latest version. Maybe I forgot to publish? Currently traveling so can't check. Could you also check tb-reducer --version?

**Comment by Ademord** [comment]
hmm
```
ubuntu@unity-1:~/ultron/configLoader_v4/scripts$ tb-reducer --version
TensorBoard Reducer v0.2.3
```

**Comment by Ademord** [comment]
from what i see it is taking the first dir name from the list

let me clarify:
` echo event_files/run*`
gives `event_files/run61-explore event_files/run61-explore-constrained .....`

but the error shows beginning from the second one. 
`TensorBoard Reducer: error: unrecognized arguments: event_files/run61-explore-constrained ... ` so it is taking the first dict into that param of `in_dirs = glob("glob_pattern/of_directories_to_reduce*")` instead of the whole list of folders... ?

**Comment by janosh** [comment]
Alright, back at my laptop. This is entirely my fault. I indeed forgot to publish a new version since... much too long.

Please try `pip install -U tensorboard-reducer` again to get the just released [v0.2.4](https://pypi.org/project/tensorboard-reducer/0.2.4) and see if it works then.

**Comment by Ademord** [comment]
i am super grateful that you took time during your holidays for this.

my current error has moved to
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tb-reducer", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorboard_reducer/main.py", line 136, in main
    events_dict = load_tb_events(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tensorboard_reducer/load.py", line 75, in load_tb_events
    assert all_runs_same_tags, (
AssertionError: Some tags appear in some TB logs but not others:
- event_files/run61-explore missing tags: Policy/Curiosity Reward, Policy/Curiosity Value Estimate, Losses/Curiosity Forward Loss, Losses/Curiosity Inverse Loss
- event_files/run61-explore-constrained missing tags: Policy/Curiosity Reward, Policy/Curiosity Value Estimate, Losses/Curiosity Forward Loss, Losses/Curiosity Inverse Loss
- event_files/run61-voxel missing tags: Policy/Curiosity Reward, Policy/Curiosity Value Estimate, Losses/Curiosity Forward Loss, Losses/Curiosity Inverse Loss
- event_files/run61-voxel-constrained missing tags: Policy/Curiosity Reward, Policy/Curiosity Value Estimate, Losses/Curiosity Forward Loss, Losses/Curiosity Inverse Loss
- event_files/run62-16 missing tags: Policy/Curiosity Reward, Policy/Curiosity Value Estimate, Losses/Curiosity Forward Loss, Losses/Curiosity Inverse Loss
- event_files/run62-16-constrained missing tags: Policy/Curiosity Reward, Policy/Curiosity Value Estimate, Losses/Curiosity Forward Loss, Losses/Curiosity Inverse Loss
- event_files/run62-16-constrained-pigeon-pathak missing tags: Policy/Curiosity Reward, Policy/Curiosity Value Estimate, Losses/Curiosity Forward Loss, Losses/Curiosity Inverse Loss
- event_files/run62-16-pathak missing tags: Policy/Curiosity Reward, Policy/Curiosity Value Estimate, Losses/Curiosity Forward Loss, Losses/Curiosity Inverse Loss
- event_files/run62-4 missing tags: Policy/Curiosity Reward, Policy/Curiosity Value Estimate, Losses/Curiosity Forward Loss, Losses/Curiosity Inverse Loss
- event_files/run62-4-pathak missing tags: 
- event_files/run62-4-pigeon missing tags: 
- event_files/run62-4-pigeon-pathak missing tags: 
- event_files/run62-8 missing tags: 
- event_files/run62-8-pathak missing tags: 
- event_files/run63 missing tags: 
- event_files/run63++025 missing tags: 
- event_files/run63++050 missing tags: 
- event_files/run63++075 missing tags: 
- event_files/run63++100 missing tags: 
- event_files/run64 missing tags: 
- event_files/run64+vision missing tags: 
- event_files/run65 missing tags: 
- event_files/run65-pure missing tags: 
```
i find this interesting, also the empty tags warning? 
i used --lax-tags and --lax-steps but now i am surprised that the result is something i guess i didnt not expect but this is my own mistake. the aggregator/reducer reduces all the runs to "one run". 

i am looking for a way to generate a mean/std/min/max per run. (so run62 -- mean 0.5, etc). sorry for not getting that right away from this.

**Comment by janosh** [comment]
> i am looking for a way to generate a mean/std/min/max per run. (so run62 -- mean 0.5, etc). sorry for not getting that right away from your readme.

Interesting, I never considered that. What's your use case? I guess we could add the ability to reduce along the step dimension rather than across runs.

**Comment by Ademord** [comment]
i think thats (sorry if its the wrong word) basic use case for any paper comparing methods ? i am atm writing my results chapter of my thesis and wanted to make the tables for the comparison of the methods.

do you know how hard it would be to implement it ?

**Comment by Ademord** [comment]
so that the aggregator would take the runs in the given folder and then its easier to make a table like this

![image](https://user-images.githubusercontent.com/4501464/148661540-52a5a9a5-8f1b-4396-b77c-ef7261a7c405.png)


------ 
if you are working with dataframes even a .to_latex() print is a QoS point (brainstorming ideas right now by the way)

**Comment by Ademord** [comment]
this would mean the world by the way 🙏🏻

**Comment by janosh** [comment]
I'm confused now. TBR is exactly for creating tables like in your screenshot but to get that, you would take the mean across runs, not across steps, right?

**Comment by Ademord** [comment]
correct. accross runs. since steps are already summarized/averaged

**Comment by Ademord** [comment]
i think what confused you is that you imagine that one would make multiple runs for the same experiment and then average performances.

**Comment by janosh** [comment]
Why do you care about the mean accuracy (or whatever your metric) from start to end of training? Usually you would use TBR to compute the mean performance of a single or several similar models trained with different procedures to establish which training procedure is the best, not to check which model is the best. Or are the rows in your table repeated model inferences? But then why call them steps? Still confused.

**Comment by Ademord** [comment]
so i have different algorithms, i call them runs, since they are a run of each algorithm. 

i do not do multiple runs of the same algorithm. 

it makes sense that at the end one reports: method 1 has A% accuracy.

![image](https://user-images.githubusercontent.com/4501464/148692109-99773d55-c351-4e4f-9dc7-17d97562c14d.png)

this accuracy can only be obtained by get a the average value of the whole time series. 

right now TBR is reducing multiple runs into one, but not getting average and STD of the whole time series.

**Comment by Ademord** [comment]
each run has different metrics, also seen as dataframe columns. 

example metrics are: % of space covered, new nodes discovery rate, etc

the statistics  i need are the dataframe["column"].average(), for each run

**Comment by Ademord** [comment]
```
def convert_tb_data(root_dir, sort_by=None):
    """Convert local TensorBoard data into Pandas DataFrame.

    Function takes the root directory path and recursively parses
    all events data.
    If the `sort_by` value is provided then it will use that column
    to sort values; typically `wall_time` or `step`.

    *Note* that the whole data is converted into a DataFrame.
    Depending on the data size this might take a while. If it takes
    too long then narrow it to some sub-directories.

    Paramters:
        root_dir: (str) path to root dir with tensorboard data.
        sort_by: (optional str) column name to sort by.

    Returns:
        pandas.DataFrame with [wall_time, name, step, value] columns.

    """
    import os
    import pandas as pd
    from tensorflow.python.summary.summary_iterator import summary_iterator

    def convert_tfevent(filepath):
        return pd.DataFrame([
            parse_tfevent(e) for e in summary_iterator(filepath) if len(e.summary.value)
        ])

    def parse_tfevent(tfevent):
        return dict(
            wall_time=tfevent.wall_time,
            name=tfevent.summary.value[0].tag,
            step=tfevent.step,
            value=float(tfevent.summary.value[0].simple_value),
        )

    columns_order = ['wall_time', 'name', 'step', 'value']

    out = []
    for (root, _, filenames) in os.walk(root_dir):
        for filename in filenames:
            if "events.out.tfevents" not in filename:
                continue
            file_full_path = os.path.join(root, filename)
            df = convert_tfevent(file_full_path)

            # filter out columns that dont matter
            df = df[df['name'].str.contains("Drone/")]
            df = df[df['step'] > 5000000]
            # remove unnecessary columns
            df = df.drop('wall_time', 1)
            df = df.drop('step', 1)

            # df = df.loc[:, df.columns.str.contains('Drone/')]
            # group to collect means of
            df = df.groupby(['name']).mean().reset_index() # .unstack(level=0).apply(lambda x: x)
            # df = df.groupby(['name'])
            # get run name
            run_name = filename[:filename.index(".")]
            # add run name as suffix
            df = df.add_suffix(run_name)
            #
            out.append(df)

    # Concatenate (and sort) all partial individual dataframes


    all_df = pd.concat(out)[columns_order]
    if sort_by is not None:
        all_df = all_df.sort_values(sort_by)

    return all_df.reset_index(drop=True)

if __name__ == "__main__":
    dir_path = "./logs"
    df = convert_tb_data(dir_path)

    print(df.head())
```


This loads an event file and gets the average of the run. I need to finish it so that it doesnt concat all of the runs into one.

**Comment by Ademord** [comment]
if you'd like my code to make a pull request somehow let me know.

**Comment by janosh** [comment]
I think a PR is not necessary since it seems a very particular use case. I was also careful not to depend on TensorFlow in this package which your function uses so it wouldn't work in its current implementation.

Good thing you solved your problem, though! 👍
